# Work in progress...

name: wheels

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7]
        numpy-version: [1.15, 1.16, 1.17]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install numpy==${{ matrix.numpy-version }}
    - name: Install ufunclab
      run: |
        git submodule init
        git submodule update
        cd ufunclab
        pwd
        pip install .
    - name: Run multibuild scripts
      run: |
        pwd
        ls
        source multibuild/common_utils.sh
        # Not running on TravisCI, but try it anyway...
        source multibuild/travis_steps.sh
        before_install
