# Work in progress...

name: wheels

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7]
        numpy-version: [1.15, 1.16, 1.17]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel virtualenv
        pip install numpy==${{ matrix.numpy-version }}
    - name: Initialize git submodules
      run: |
        git submodule init
        git submodule update
    - name: multibuild scripts
      env:
        REPO_DIR: ufunclab
        BUILD_COMMIT: c1bba4c6997885d3f14b6869994d53b758322680
        BUILD_DEPENDS: numpy
        MB_PYTHON_VERSION: ${{ matrix.python-version }}
        MB_ML_VER: 2010
      run: |
        pwd
        source multibuild/common_utils.sh
        # Not running on TravisCI, but try it anyway...
        source multibuild/travis_steps.sh
        before_install
        clean_code $REPO_DIR $BUILD_COMMIT
        build_wheel $REPO_DIR $PLAT
        ls
        ls -l wheelhouse

